apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: r2kwb8z8h-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: r2kwb8z8h-go 
  name: r2kwb8z8h-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: r2kwb8z8h-go 
